// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRPrTN6fuy-oJ2XimqBllpuFRmTTT73CU',
    appId: '1:865755466850:web:7ec6da137e01193b34953b',
    messagingSenderId: '865755466850',
    projectId: 'btg-funds-manager',
    authDomain: 'btg-funds-manager.firebaseapp.com',
    storageBucket: 'btg-funds-manager.firebasestorage.app',
    measurementId: 'G-5D4F23GHES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnn-ZN8DDbFsIFpt-co36d-jhHZR6Ma7g',
    appId: '1:865755466850:android:c3678a7e2163562534953b',
    messagingSenderId: '865755466850',
    projectId: 'btg-funds-manager',
    storageBucket: 'btg-funds-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbhJiXOq2bkz5jgAljkze0Q5YFgMb8tIo',
    appId: '1:865755466850:ios:0fe25ed443520c8e34953b',
    messagingSenderId: '865755466850',
    projectId: 'btg-funds-manager',
    storageBucket: 'btg-funds-manager.firebasestorage.app',
    iosBundleId: 'com.btgfundsmanager.flutter.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRPrTN6fuy-oJ2XimqBllpuFRmTTT73CU',
    appId: '1:865755466850:web:0ec6ad327fcb839a34953b',
    messagingSenderId: '865755466850',
    projectId: 'btg-funds-manager',
    authDomain: 'btg-funds-manager.firebaseapp.com',
    storageBucket: 'btg-funds-manager.firebasestorage.app',
    measurementId: 'G-6XLCP47JLY',
  );
}
